name: Update 

on:
  schedule:
    - cron: '10 13 * * 1-5'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Fetch data
        run: |
          sudo apt-get install -y libarchive-tools tree
          mkdir data
          wget -qO- $(curl https://covid19.ssi.dk/overvagningsdata/download-fil-med-overvaagningdata | grep $(date +"%d%m%Y") | grep -v dashboard | grep -oP 'https://[^"]*') | bsdtar -xvf- -C data
          mv data/Rt_cases* data/Rt_cases.csv

      - name: Generate index
        run: |
          tree -H '.' -L 1 --noreport --charset utf-8 -o data/index.html data

      - name: Publish to GitHub pages
        run: |
          git clone https://fuglede:$TOKEN@github.com/fuglede/covid-19-dk-data.git --branch gh-pages --single-branch gh-pages
          cd gh-pages
          cp ../data/* .
          touch .nojekyll
          git config --local user.email "github@fuglede.dk"
          git config --local user.name "Søren Fuglede Jørgensen"
          git add .
          git commit -m "Publish static files" --amend
          git push -f
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
